name: CI

on:
  push:
  pull_request:

jobs:
  build-and-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Uncrustify
        run: sudo apt-get update && sudo apt-get install -y uncrustify

      - name: Run Uncrustify style check
        run: |
          # Only check within specific folders
          files=$(find drivers samples tests sources cli \
            -type f \( -name '*.c' -o -name '*.h' \))

          echo "Checking style for:"
          echo "$files"

          failed=0
          for f in $files; do
            if ! uncrustify -c tools/uncrustify.cfg --check "$f"; then
              echo "❌ Style check failed for $f"
              failed=1
            fi
          done

          if [ $failed -ne 0 ]; then
            echo "Some files failed style check ❌"
            exit 1
          else
            echo "All files passed style check ✅"
          fi
