name: Code Style Check

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Uncrustify
        run: sudo apt-get install -y uncrustify

      - name: Run Uncrustify check
        run: |
          files=$(find . -name '*.c' -o -name '*.h')
          for f in $files; do
            uncrustify -c tools/uncrustify.cfg --check $f || exit 1
          done

